spring:
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/imdb
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090
